// <auto-generated/>
#pragma warning disable CS0618
using GitHub.Enterprise.Stats.All;
using GitHub.Enterprise.Stats.Comments;
using GitHub.Enterprise.Stats.Gists;
using GitHub.Enterprise.Stats.Hooks;
using GitHub.Enterprise.Stats.Issues;
using GitHub.Enterprise.Stats.Milestones;
using GitHub.Enterprise.Stats.Orgs;
using GitHub.Enterprise.Stats.Pages;
using GitHub.Enterprise.Stats.Pulls;
using GitHub.Enterprise.Stats.Repos;
using GitHub.Enterprise.Stats.SecurityProducts;
using GitHub.Enterprise.Stats.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.Enterprise.Stats
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprise\stats
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class StatsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public global::GitHub.Enterprise.Stats.All.AllRequestBuilder All
        {
            get => new global::GitHub.Enterprise.Stats.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The comments property</summary>
        public global::GitHub.Enterprise.Stats.Comments.CommentsRequestBuilder Comments
        {
            get => new global::GitHub.Enterprise.Stats.Comments.CommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gists property</summary>
        public global::GitHub.Enterprise.Stats.Gists.GistsRequestBuilder Gists
        {
            get => new global::GitHub.Enterprise.Stats.Gists.GistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hooks property</summary>
        public global::GitHub.Enterprise.Stats.Hooks.HooksRequestBuilder Hooks
        {
            get => new global::GitHub.Enterprise.Stats.Hooks.HooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issues property</summary>
        public global::GitHub.Enterprise.Stats.Issues.IssuesRequestBuilder Issues
        {
            get => new global::GitHub.Enterprise.Stats.Issues.IssuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The milestones property</summary>
        public global::GitHub.Enterprise.Stats.Milestones.MilestonesRequestBuilder Milestones
        {
            get => new global::GitHub.Enterprise.Stats.Milestones.MilestonesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orgs property</summary>
        public global::GitHub.Enterprise.Stats.Orgs.OrgsRequestBuilder Orgs
        {
            get => new global::GitHub.Enterprise.Stats.Orgs.OrgsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pages property</summary>
        public global::GitHub.Enterprise.Stats.Pages.PagesRequestBuilder Pages
        {
            get => new global::GitHub.Enterprise.Stats.Pages.PagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pulls property</summary>
        public global::GitHub.Enterprise.Stats.Pulls.PullsRequestBuilder Pulls
        {
            get => new global::GitHub.Enterprise.Stats.Pulls.PullsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repos property</summary>
        public global::GitHub.Enterprise.Stats.Repos.ReposRequestBuilder Repos
        {
            get => new global::GitHub.Enterprise.Stats.Repos.ReposRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The securityProducts property</summary>
        public global::GitHub.Enterprise.Stats.SecurityProducts.SecurityProductsRequestBuilder SecurityProducts
        {
            get => new global::GitHub.Enterprise.Stats.SecurityProducts.SecurityProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::GitHub.Enterprise.Stats.Users.UsersRequestBuilder Users
        {
            get => new global::GitHub.Enterprise.Stats.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Enterprise.Stats.StatsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprise/stats", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Enterprise.Stats.StatsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprise/stats", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
