// <auto-generated/>
#pragma warning disable CS0618
using GitHub.Admin.Ldap.Teams.Item.Mapping;
using GitHub.Admin.Ldap.Teams.Item.Sync;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.Admin.Ldap.Teams.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \admin\ldap\teams\{team_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class WithTeam_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The mapping property</summary>
        public global::GitHub.Admin.Ldap.Teams.Item.Mapping.MappingRequestBuilder Mapping
        {
            get => new global::GitHub.Admin.Ldap.Teams.Item.Mapping.MappingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sync property</summary>
        public global::GitHub.Admin.Ldap.Teams.Item.Sync.SyncRequestBuilder Sync
        {
            get => new global::GitHub.Admin.Ldap.Teams.Item.Sync.SyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Admin.Ldap.Teams.Item.WithTeam_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTeam_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/ldap/teams/{team_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Admin.Ldap.Teams.Item.WithTeam_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTeam_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/ldap/teams/{team_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
