// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace GitHub.Models {
    #pragma warning disable CS1591
    public class GhesChecksSystemRequirements : IAdditionalDataHolder, IParsable 
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The nodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<GhesChecksSystemRequirements_nodes>? Nodes { get; set; }
#nullable restore
#else
        public List<GhesChecksSystemRequirements_nodes> Nodes { get; set; }
#endif
        /// <summary>The status property</summary>
        public GhesChecksResultIndicator? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="GhesChecksSystemRequirements"/> and sets the default values.
        /// </summary>
        public GhesChecksSystemRequirements()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="GhesChecksSystemRequirements"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static GhesChecksSystemRequirements CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new GhesChecksSystemRequirements();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"nodes", n => { Nodes = n.GetCollectionOfObjectValues<GhesChecksSystemRequirements_nodes>(GhesChecksSystemRequirements_nodes.CreateFromDiscriminatorValue)?.ToList(); } },
                {"status", n => { Status = n.GetEnumValue<GhesChecksResultIndicator>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<GhesChecksSystemRequirements_nodes>("nodes", Nodes);
            writer.WriteEnumValue<GhesChecksResultIndicator>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
