// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum GhesClusterTopology
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SingleNode")]
        #pragma warning disable CS1591
        SingleNode,
        #pragma warning restore CS1591
        [EnumMember(Value = "Ha")]
        #pragma warning disable CS1591
        Ha,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cluster")]
        #pragma warning disable CS1591
        Cluster,
        #pragma warning restore CS1591
    }
}
