// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GhesClusterRoles
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Blank")]
        #pragma warning disable CS1591
        Blank,
        #pragma warning restore CS1591
        [EnumMember(Value = "ActionsServer")]
        #pragma warning disable CS1591
        ActionsServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "ConsulServer")]
        #pragma warning disable CS1591
        ConsulServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "ElasticsearchServer")]
        #pragma warning disable CS1591
        ElasticsearchServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "GitServer")]
        #pragma warning disable CS1591
        GitServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "JobServer")]
        #pragma warning disable CS1591
        JobServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "LaunchServer")]
        #pragma warning disable CS1591
        LaunchServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "MemcacheServer")]
        #pragma warning disable CS1591
        MemcacheServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "MetricsServer")]
        #pragma warning disable CS1591
        MetricsServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "MssqlServer")]
        #pragma warning disable CS1591
        MssqlServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "MysqlServer")]
        #pragma warning disable CS1591
        MysqlServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "PagesServer")]
        #pragma warning disable CS1591
        PagesServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "RedisServer")]
        #pragma warning disable CS1591
        RedisServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "StorageServer")]
        #pragma warning disable CS1591
        StorageServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "WebServer")]
        #pragma warning disable CS1591
        WebServer,
        #pragma warning restore CS1591
    }
}
