// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models {
    #pragma warning disable CS1591
    public enum GhesChecksResultIndicator
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "OK")]
        #pragma warning disable CS1591
        OK,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAILED")]
        #pragma warning disable CS1591
        FAILED,
        #pragma warning restore CS1591
    }
}
