// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    /// <summary>The license status of the currently active enterprise license.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public enum GhesLicenseCheck_status
    {
        [EnumMember(Value = "valid")]
        #pragma warning disable CS1591
        Valid,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid")]
        #pragma warning disable CS1591
        Invalid,
        #pragma warning restore CS1591
        [EnumMember(Value = "expired")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
        [EnumMember(Value = "cluster mode not supported")]
        #pragma warning disable CS1591
        ClusterModeNotSupported,
        #pragma warning restore CS1591
    }
}
