// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    #pragma warning disable CS1591
    public enum GhesClusterStatusIndicator
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "OK")]
        #pragma warning disable CS1591
        OK,
        #pragma warning restore CS1591
        [EnumMember(Value = "WARNING")]
        #pragma warning disable CS1591
        WARNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "CRITICAL")]
        #pragma warning disable CS1591
        CRITICAL,
        #pragma warning restore CS1591
    }
}
