// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum GhesVersion_version_platform
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ami")]
        #pragma warning disable CS1591
        Ami,
        #pragma warning restore CS1591
        [EnumMember(Value = "azure")]
        #pragma warning disable CS1591
        Azure,
        #pragma warning restore CS1591
        [EnumMember(Value = "esx")]
        #pragma warning disable CS1591
        Esx,
        #pragma warning restore CS1591
        [EnumMember(Value = "gce")]
        #pragma warning disable CS1591
        Gce,
        #pragma warning restore CS1591
        [EnumMember(Value = "hyperv")]
        #pragma warning disable CS1591
        Hyperv,
        #pragma warning restore CS1591
        [EnumMember(Value = "kvm")]
        #pragma warning disable CS1591
        Kvm,
        #pragma warning restore CS1591
    }
}
