// <auto-generated/>
using GitHub.Manage.V1.Access;
using GitHub.Manage.V1.Checks;
using GitHub.Manage.V1.Config;
using GitHub.Manage.V1.Maintenance;
using GitHub.Manage.V1.Replication;
using GitHub.Manage.V1.VersionNamespace;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace GitHub.Manage.V1 {
    /// <summary>
    /// Builds and executes requests for operations under \manage\v1
    /// </summary>
    public class V1RequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The access property</summary>
        public AccessRequestBuilder Access
        {
            get => new AccessRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The checks property</summary>
        public ChecksRequestBuilder Checks
        {
            get => new ChecksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The config property</summary>
        public ConfigRequestBuilder Config
        {
            get => new ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The maintenance property</summary>
        public MaintenanceRequestBuilder Maintenance
        {
            get => new MaintenanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The replication property</summary>
        public ReplicationRequestBuilder Replication
        {
            get => new ReplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The version property</summary>
        public VersionRequestBuilder Version
        {
            get => new VersionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/manage/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/manage/v1", rawUrl)
        {
        }
    }
}
