// <auto-generated/>
using GitHub.Admin.Ldap.Teams.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace GitHub.Admin.Ldap.Teams {
    /// <summary>
    /// Builds and executes requests for operations under \admin\ldap\teams
    /// </summary>
    public class TeamsRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the GitHub.admin.ldap.teams.item collection</summary>
        /// <param name="position">The unique identifier of the team.</param>
        /// <returns>A <see cref="WithTeam_ItemRequestBuilder"/></returns>
        public WithTeam_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("team_id", position);
                return new WithTeam_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="TeamsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TeamsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/ldap/teams", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="TeamsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TeamsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/admin/ldap/teams", rawUrl)
        {
        }
    }
}
