// <auto-generated/>
using GitHub.Authorizations.Clients.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace GitHub.Authorizations.Clients {
    /// <summary>
    /// Builds and executes requests for operations under \authorizations\clients
    /// </summary>
    public class ClientsRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the GitHub.authorizations.clients.item collection</summary>
        /// <param name="position">The client ID of the OAuth app.</param>
        /// <returns>A <see cref="WithClient_ItemRequestBuilder"/></returns>
        [Obsolete("")]
        public WithClient_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("client_id", position);
                return new WithClient_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="ClientsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/authorizations/clients", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ClientsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/authorizations/clients", rawUrl)
        {
        }
    }
}
