// <auto-generated/>
using GitHub.Setup.Api;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace GitHub.Setup {
    /// <summary>
    /// Builds and executes requests for operations under \setup
    /// </summary>
    public class SetupRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>The api property</summary>
        public ApiRequestBuilder Api
        {
            get => new ApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="SetupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SetupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/setup", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="SetupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SetupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/setup", rawUrl)
        {
        }
    }
}
