// <auto-generated/>
#pragma warning disable CS0618
using GitHub.Enterprises.Item.Settings.Billing.AdvancedSecurity;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.Enterprises.Item.Settings.Billing
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\settings\billing
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class BillingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The advancedSecurity property</summary>
        public global::GitHub.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder AdvancedSecurity
        {
            get => new global::GitHub.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Enterprises.Item.Settings.Billing.BillingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BillingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/settings/billing", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Enterprises.Item.Settings.Billing.BillingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BillingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/settings/billing", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
