// <auto-generated/>
#pragma warning disable CS0618
using GitHub.Enterprise.Announcement;
using GitHub.Enterprise.Settings;
using GitHub.Enterprise.Stats;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.Enterprise
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprise
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.19.0")]
    public partial class EnterpriseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The announcement property</summary>
        public global::GitHub.Enterprise.Announcement.AnnouncementRequestBuilder Announcement
        {
            get => new global::GitHub.Enterprise.Announcement.AnnouncementRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::GitHub.Enterprise.Settings.SettingsRequestBuilder Settings
        {
            get => new global::GitHub.Enterprise.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stats property</summary>
        public global::GitHub.Enterprise.Stats.StatsRequestBuilder Stats
        {
            get => new global::GitHub.Enterprise.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Enterprise.EnterpriseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnterpriseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprise", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Enterprise.EnterpriseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EnterpriseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprise", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
